language: go

go:
  - 1.16.x
  - 1.17.x
  - 1.18.x
  - master

after_success: |
  go test -race -coverprofile=coverage.txt -covermode=atomic &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
